baseURL = 'https://melbournewiderenovations.com.au/'
languageCode = 'en-us'
theme = 'graysx'
title = 'MelbourneWideRenovations * Site PoweredBy Bespokelink Ltd *'

## Site Settings
[params]
logo = "assets/img/white_transparent_logo.png"
favicon = "assets/favicongreen.png"

# Info
address = "Melbourne Australia"
email = "info@melbournewiderenovations.com.au"
phone = "03 9923 7800"
location = "https://www.google.com/maps/place/Melbourne+VIC,+Australia/@-37.9696427,144.3936765,9z/data=!3m1!4b1!4m6!3m5!1s0x6ad646b5d2ba4df7:0x4045675218ccd90!8m2!3d-37.8136276!4d144.9630576!16zL20vMGNoZ3pt?entry=ttu"

# Socials

instagram = "https://www.instagram.com/melbournewiderenovations?igsh=MXFjb2xjeWFhZHZ1aQ=="
facebook = "https://www.facebook.com/share/SBCns4DQQPxzvtit/?mibextid=qi2Omg"
github = "https://github.com/akatiggerx04/graysx-hugo"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Expertise"
  URL = "#expertise"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04